version: '3'

services:
  spring-tutorial:
    image: spring-boot-tutorial:0.0.6-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=project
    ports:
      - "27017:27017"

