apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo-config-server
  name: demo-config-server
spec:
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: demo-config-server
status:
  loadBalancer: {}